#!/usr/bin/python3

import subprocess
import sys

'''
 Should replace apt command with python-apt module.
'''

  
def install(packages, script):
    if script:
        process = subprocess.Popen(['sh', packages[0]])
    else:
        process = subprocess.Popen(['apt', 'install', '--allow-unauthenticated', '-y'] + packages)
    retval = process.wait()
    
    return retval

def remove(packages):
    process = subprocess.Popen(['apt', 'remove', '-y'] + packages)
    retval = process.wait()
    
    return retval
    
    
if __name__ == "__main__":
   
    args = sys.argv
    
    if len(args) < 3:
        print("Expected arguments not found")
        sys.exit(-1)
    
    action = args[1]
    
    script = False
    if args[2] == 'True':
        script = True
        
    packages = args[3:]
     
    print("[DEBUG] action : {}, script : {}, packages : {}".format(action, script, ", ".join(packages)))
    
    if action == 'INSTALL':
        retval = install(packages, script)
    elif action == 'REMOVE':
        retval = remove(packages)
        
    sys.exit(retval)
