#! /usr/bin/python3
# -*- coding:utf-8 -*-
#
# Copyright 2012-2013 "Korora Project" <dev@kororaproject.org>
# Copyright 2013 "Manjaro Linux" <support@manjaro.org>
# Copyright 2014 Antergos
# Copyright 2016 Bugie Remix
#
# Budgie Remix Welcome is free software: you can redistribute it and/or modify
# it under the temms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Budgie Remix Welcome is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Budgie Remix Welcome. If not, see <http://www.gnu.org/licenses/>.
#

""" Welcome screen for Budgie Remix """

import gi
gi.require_version('WebKit', '3.0')

import inspect
import os
# import json
import signal
import subprocess
import sys
import urllib.request
import urllib.error
import webbrowser

from simplejson import dumps as to_json

from gi.repository import WebKit, Gtk


class WelcomeConfig(object):

    """ Manages Welcome configuration """

    def __init__(self):
        # store our base architecture
        if os.uname()[4] == 'x86_64':
            self._arch = '64-bit'
        else:
            self._arch = '32-bit'

        # store we are a live CD session
        self._live = (os.path.exists('/bootmnt/antergos'))

        # store full path to our binary
        self._welcome_bin_path = os.path.abspath(inspect.getfile(
            inspect.currentframe()))

        # store directory to our welcome configuration
        self._config_dir = os.path.expanduser('~/.config/antergos/welcome/')

        # store full path to our autostart symlink
        self._autostart_path = os.path.expanduser(
            '~/.config/autostart/antergos-welcome.desktop')

        # ensure our config directory exists
        if not os.path.exists(self._config_dir):
            try:
                os.makedirs(self._config_dir)
            except OSError:
                pass
        # does autostart symlink exist
        self._autostart = os.path.exists(self._autostart_path)

        # Hard code distribution name for time being. Later
        # access it using `lsb_release` command.
        self._distroname = 'Budgie Remix'

    @property
    def arch(self):
        return self._arch

    @property
    def autostart(self):
        return self._autostart

    @autostart.setter
    def autostart(self, state):
        if state and not os.path.exists(self._autostart_path):
            # create the autostart symlink
            try:
                os.symlink(
                    '/usr/share/applications/antergos-welcome.desktop',
                    self._autostart_path)
            except OSError:
                pass
        elif not state and os.path.exists(self._autostart_path):
            # remove the autostart symlink
            try:
                os.unlink(self._autostart_path)
            except OSError:
                pass

        # determine autostart state based on absence of the disable file
        self._autostart = os.path.exists(self._autostart_path)

    @property
    def live(self):
        return self._live


class AppView(WebKit.WebView):

    def __init__(self):
        WebKit.WebView.__init__(self)

        self._config = WelcomeConfig()

        self.connect('load-finished', self._load_finished_cb)
        self.connect('navigation-policy-decision-requested',
                     self._nav_request_policy_decision_cb)
        self.l_uri = None

    def _push_config(self):
        # TODO: push notification should be connected to angularjs and use a
        # broadcast event any suitable controllers will be able to listen and
        # respond accordingly, for now we just use jQuery to manually toggle

        self.execute_script("$('#arch').html('%s')" % self._config.arch)
        self.execute_script("$('#autostart').toggleClass('icon-check', {})\
            .toggleClass('icon-check-empty', {})".format(to_json
                (self._config._autostart), to_json(not self._config._autostart)))
        self.execute_script("$('span[name=\"distro-name\"]').html('{}')".format(self._config._distroname))


        # if self._config.desktop == 'GNOME':
        #  self.execute_script("$('#gnome_help').toggleClass('hide', false);")
        # elif self._config.desktop == 'KDE':
        #  self.execute_script("$('#kde_help').toggleClass('hide', false);")

        # self.execute_script("$('#codename').html('%s')" %
        #   (to_json(self._config.codename)))
        # self.execute_script("$('#desktop').html('%s')" %
        #   (to_json(self._config.desktop)))
        # self.execute_script("$('#version').html('%s')" %
        #   (self._config.version))

        if self._config.live:
            self.execute_script("$('#install').toggleClass('hide', false);")
            self.execute_script(
                "$('#install-cli').toggleClass('hide', false);")
        else:
            self.execute_script("$('#build').toggleClass('hide', false);")
            self.execute_script("$('#donate').toggleClass('hide', false);")

    def _load_finished_cb(self, view, frame):
        self._push_config()

    def _nav_request_policy_decision_cb(self, view, frame, net_req, nav_act,
                                        pol_dec):
        uri = net_req.get_uri()

        try:
            if uri.index('#') > 0:
                uri = uri[:uri.index('#')]
        except ValueError:
            pass

        if uri == self.l_uri:
            pol_dec.use()
            return True

        if uri.startswith('cmd://'):
            self._do_command(uri)
            return True

        self.l_uri = uri

        page = urllib.request.urlopen(uri)
        frame.load_string(page.read().decode(),
                          "text/html", "iso-8859-15", page.geturl())
        pol_dec.ignore()
        return True

    def _do_command(self, uri):
        if uri.startswith('cmd://'):
            uri = uri[6:]

        if uri == 'gnome-help':
            subprocess.Popen(['yelp'])
        elif uri == 'kde-help':
            subprocess.Popen(['khelpcenter'])
        # elif uri == 'install':
            # subprocess.Popen(['sudo','live-installer'])
        # elif uri == 'install-cli':
            # subprocess.Popen(['xdg-terminal','sudo setup'])
        elif uri == 'close':
            Gtk.main_quit()
        elif uri == 'toggle-startup':
            # toggle autostart
            self._config.autostart ^= True
            self._push_config()
        elif uri.startswith("link?"):
            webbrowser.open_new_tab(uri[5:])
        else:
            print('Unknown command: %s' % uri)


class WelcomeApp(object):

    def __init__(self):
        # establish our location
        self._location = os.path.dirname(
            os.path.abspath(inspect.getfile(inspect.currentframe())))

        # check for relative path
        if(os.path.exists(os.path.join(self._location, 'data/'))):
            print('Using relative path for data source.\
                   Non-production testing.')
            self._data_path = os.path.join(self._location, 'data/')
        elif(os.path.exists('/usr/share/antergos-welcome/')):
            print('Using /usr/share/antergos-welcome/ path.')
            self._data_path = '/usr/share/antergos-welcome/'
        else:
            print('Unable to source the antergos-welcome data directory.')
            sys.exit(1)

        self._build_app()

    def _build_app(self):
        # build window
        w = Gtk.Window()
        w.set_position(Gtk.WindowPosition.CENTER)
        w.set_wmclass('Budgie Remix Welcome', 'Budgie Remix Welcome')
        w.set_title('')
        w.set_size_request(992, 520)
        # w.set_decorated(False)

        icon_dir = os.path.join(self._data_path, 'img', 'distro-icon.svg')
        w.set_icon_from_file(icon_dir)

        # build webkit container
        mv = AppView()

        # load our index file
        file = os.path.abspath(os.path.join(self._data_path, 'index.html'))
        uri = 'file://' + urllib.request.pathname2url(file)
        mv.open(uri)

        # build scrolled window widget and add our appview container
        sw = Gtk.ScrolledWindow()
        sw.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        sw.add(mv)

        # build a an autoexpanding box and add our scrolled window
        b = Gtk.VBox(homogeneous=False, spacing=0)
        b.pack_start(sw, expand=True, fill=True, padding=0)

        # add the box to the parent window and show
        w.add(b)
        w.connect('delete-event', self.close)
        w.show_all()

        self._window = w
        self._appView = mv

    def run(self):
        signal.signal(signal.SIGINT, signal.SIG_DFL)
        Gtk.main()

    def close(self, p1, p2):
        Gtk.main_quit(p1, p2)

app = WelcomeApp()
app.run()
